baseURL = "https://hack13.me"
languageCode = "en-us"
title = "Hack13 Blog"
theme = "hacksite"
sectionPagesMenu = "main"

[menu]
[[menu.main]]
    identifier = "home"
    name = "Home"
    title = "home"
    weight = "10"
    url = "/"
[[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "posts"
    weight = "15"
    url = "/posts/"