on: push
name: Build and deploy
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@master
    - name: Build hugo site
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    - name: Upload files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/