on: push
name: Build and deploy
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Build hugo site
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    - name: Clean permissions
      uses: main-quest/actions.clean-permissions@v1.0.4
    - name: Upload files
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        username: ${{ secrets.SFTP_USERNAME }}
        host: ${{ secrets.SFTP_SERVER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
        localDir: './public/*'
        remoteDir: ${{ secrets.SFTP_REMOTE_PATH }}